# ## Get all orders
# GET http://localhost:5136/api/v1/orders

POST http://localhost:5136/api/v1/orders
Content-Type: application/json

{
  "fullName": "string",
  "deliveryAddress": "string",
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "orderDetails": [
    {
      "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quantity": 0
    }
  ]
}


