
## create a new product
POST http://localhost:5136/api/v1/products
Content-Type: application/json

{
  "productName": "string",
  "price": 0,
  "stock": 0,
  "description": "string",
  "productImages": [
    {
      "link": "string"
    }
  ]
}

### Get all products
GET http://localhost:5136/api/v1/products